dev-inc:
  target: dev
  outputs:
    dev:
      type: postgres
      host: http://localhost
      user: dbt
      password: password
      port: 5432
      dbname: postgres # or database instead of dbname
      schema: public
      keepalives_idle: 0 # default 0, indicating the system default. See below
      connect_timeout: 10 # default 10 seconds